felangel/equatable

example/main.dart
lib/src/equatable.dart
test/equatable_test.dart

**READY**
NO
Added a default `toString` override which returns the string representation of props.
None

add toString override

---

lib/src/equatable_utils.dart
test/custom_list.dart
test/equatable_test.dart

**READY**
**NONE**
see my sample repo to demonstrate the issue:
https://github.com/dustin-graham/dart_equality_sample
In short, two Lists can have identical contents but the Lists themselves can have different runtimeTypes. This is OK. To illustrate this, the provided sample code shows that the [Collection](https://pub.dev/packages/collection) package believes that the two lists, while of a different runtimeType are equal. However, the latest release of this package prevents these two lists from being compared, which produces the false negative.
The check on the runtimeType for all objects is a good idea, but collections are a special case in that we're primarily concerned that the _contents_ of the collections are equal, rather than concerned that the concrete implementations of the …

perform runtime check only for non-collection types

---

CHANGELOG.md
example/pubspec.yaml
lib/src/equatable.dart
lib/src/equatable_mixin.dart
pubspec.yaml
test/equatable_mixin_test.dart
test/equatable_test.dart

**READY**
YES
Addresses #25
- `Equatable` and `EquatableMixinBase` enforce immutability.
- Remove `toString` overrides
None

Enforce Immutability

---

CHANGELOG.md
lib/src/equatable.dart
lib/src/equatable_mixin.dart
pubspec.yaml
test/equatable_mixin_test.dart
test/equatable_test.dart

**READY**
YES
Update `toString` to default to `runtimeType` (#27)
None

equatable v0.4.0

---

CHANGELOG.md
README.md
example/main.dart
lib/src/equatable_mixin.dart
pubspec.yaml
test/equatable_mixin_test.dart

**READY**
YES
It removes `EquatableMixinBase` by making it built-in `EquatableMixin` 
Outline the steps to test or reproduce the PR here.
```dart
class Foo with EquatableMixinBase, EquatableMixin {
Foo(this.a);
final int a;
@override
List<Object> get props => [a];
}
```
now becomes:
```dart
class Foo with EquatableMixin {
Foo(this.a);
final int a;
@override
List<Object> get props => [a];
}
```

remove EquatableMixinBase

---

README.md

READY
NO
It seems the correct version is 0.6.1 and not 0.6.0 since many will probably copy and paste from the documentation, it makes sense to make it align with the correct number. Perhaps you may need to even release one more time with the correct version. 
This PR will affect nothing expect it will correct documentation
Thanks for your great work!

aligning readme with package version

---

CHANGELOG.md
lib/src/equatable_utils.dart
pubspec.yaml
test/equatable_mixin_test.dart
test/equatable_test.dart

**READY**
NO
- Use [Jenkins Hash](https://en.wikipedia.org/wiki/Jenkins_hash_function) instead of XOR to reduce collisions (#39)
- Reduce hash collisions

Use Jenkins Hash

---

CHANGELOG.md
lib/src/equatable_utils.dart
pubspec.yaml
test/equatable_test.dart

**READY**
NO
- Fix `hashCode` collision for `Map` props (#43)
- Bugfix which will be included in v1.0.1

Fix Map HashCode Collision

---

lib/src/equatable_utils.dart
test/equatable_mixin_test.dart

READY
NO
Fixing the issue with similar hashCodes for objects with equal lists but different values. Props list contains the lists as last item. Related Issue number: #49.

#49: Fixed issue with equal lists

---

README.md
example/main.dart
lib/src/equatable.dart
lib/src/equatable_mixin.dart
lib/src/equatable_utils.dart
test/equatable_mixin_test.dart
test/equatable_test.dart

READY
NO
I implemented the `toString` method feature using the props. 
I think it is a very useful feature for testing and debugging that most of developers that use this library would like to use.  It could be able to do this through an own subclass of equatable or another library but I think that it is overkill for this small feature. This library override already that method and there is no impact implementing this.
No related PRs.
There is no TODOs
This new feature will not have impact in the code base, functionality or performance.
It is disabled by default and does not force the user to do changes.

Implement toString feature

---

CHANGELOG.md
pubspec.yaml

READY
NO
I was not sure if I had to increase the version and update the change log in my previous PR: https://github.com/felangel/equatable/pull/45/
Since we fixed the `hashCode` error when props is null, I think it could be interesting release those changes soon.

Increase minor version to release hashCode fix and toString feature

---

CHANGELOG.md
README.md
lib/equatable.dart
lib/src/equatable.dart
lib/src/equatable_config.dart
lib/src/equatable_mixin.dart
pubspec.yaml
test/equatable_config_test.dart
test/equatable_mixin_test.dart
test/equatable_test.dart

**READY**
NO
Addresses #68 #60 #65 
`stringify` can be configured globally for all `Equatable` instances via `EquatableConfig`
```dart
EquatableConfig.stringify = true;
```
If `stringify` is overridden for a specific `Equatable` class, then the value of `EquatableConfig.stringify` is ignored.
In other words, the local configuration always takes precedence over the global configuration.
New feature which will be included in v1.2.0 of `Equatable`.

feat: EquatableConfig for global stringify configuration

---

example/main.dart
lib/src/equatable_utils.dart
test/equatable_test.dart

**READY**
NO
Before fixing, SingleEquatable with a list of zeros returns the same hashcode not depends on how much zeros in it. (closes #74)
- [+] Tests
- [+] Examples
Outline the steps to test or reproduce the PR here.
Please, look at this issue: https://github.com/felangel/equatable/issues/74
```
```

Iterable hashCode fix

---

lib/equatable.dart
lib/src/equatable.dart
lib/src/equatable_config.dart
lib/src/equatable_mixin.dart

**READY**
NO
When projects that use this library have strict rules around documentation verification (for example, when checking docs in CI), this library makes that CI pipeline fail in some cases. When generating documentation for this library, some warnings arise such as invalid references to symbols (`[Equatables]` doesn't exist, but `[Equatable]` does). This might prevent the aforementioned libraries from getting their docs generated once uploaded to [pub.dev](https://pub.dev/).
An example of this behavior can be found on [the score page of my package KanaKit](https://pub.dev/packages/kana_kit/score).
10 points are deducted from the score, no docs are generated and the following warnings are given:
```
warning: unresolved doc reference [Equatables]
from kana_kit.KanaKitConfig.props: …
```

docs: improve and fix public docs

---

CHANGELOG.md
lib/src/equatable.dart
pubspec.yaml

**READY**
NO
- docs: fix dartdoc warnings (closes #80)
- released as v1.2.5

docs: fix dartdoc warnings

---

lib/src/equatable.dart

Replace "properies" to "properties"
**READY**
NO
Just fixing a typo
.
branch | PR
------ | ------
.
.
Outline the steps to test or reproduce the PR here.
.
* None

fix typo in equatable documentation

---

lib/src/equatable_utils.dart
test/equatable_mixin_test.dart
test/equatable_test.dart

**READY**
NO
When an object only has one property and that property is null, this object will be stringified just like it has no properties, which is confusing. This pr fixes this.
Null properties will be stringified as "null" instead of ""
List related PRs against other branches:
None
Outline the steps to test or reproduce the PR here.
```
import 'package:equatable/equatable.dart';
class Test extends Equatable {
final String id;
Test(this.id);
@override
bool get stringify => true;
@override
List<Object> get props => [id];
}
void main() {
final test = Test(null);
print(test.toString());
// Test(null)
// was: Test()
}
```
* toString method of all Equatable subclasses

fix: Stringify null properties as "null" instead of ""

---

lib/src/equatable_utils.dart
test/equatable_mixin_test.dart
test/equatable_test.dart

**READY**
NO
- fix: iterable equality comparisons (closes #101)

fix: iterable equality comparisons

---

lib/src/equatable_utils.dart
test/equatable_test.dart

**READY**
NO
When calling `toString` on a long `Iterable`, dart will omit some of the elements (this is a feature), see [Iterable#toString](https://api.dart.dev/stable/2.10.4/dart-core/Iterable/toString.html).
This causes, when stringify an equatable with very long properties, some of the properties got omitted.
This pr fixes it.
#94
List related PRs against other branches:
branch | PR
------ | ------
null_safety | #98
See the test `with SuperLongProperties stringify`, the old code will not pass this test.
* `toString` method of Equatable subclasses with long enough properties and `stringify = true`

fix: stringify instance with long properties

---

.github/workflows/main.yaml
CHANGELOG.md
README.md
lib/src/equatable_config.dart
pubspec.yaml
test/equatable_config_test.dart
test/equatable_mixin_test.dart
test/equatable_test.dart

**READY**
YES
- `EquatableConfig.stringify` defaults to `true` in debug mode (closes #104)
- `EquatableConfig.stringify` can still be set manually to override the default

feat!: stringify defaults to true in debug mode

---

lib/src/equatable_mixin.dart
test/equatable_mixin_test.dart

**HOLD**
NO
- Support using `EquatableMixin` with Objects that override `==` using `dynamic` (#107)
```dart
class LegacyEqualityOverride {
const LegacyEqualityOverride(this.x);
final int x;
@override
bool operator ==(dynamic o) {
if (identical(this, o)) return true;
return o is LegacyEqualityOverride && o.x == x;
}
@override
int get hashCode => x.hashCode;
}
```

fix: support legacy equality overrides

---

CHANGELOG.md
lib/src/equatable_utils.dart
pubspec.yaml
test/equatable_test.dart

**READY**
NO
- fix: hashCode should be the same for equal objects (closes #114)

fix: hashCode should be the same for equal objects

---

lib/src/equatable_mixin.dart
test/equatable_mixin_test.dart

**READY**
YES (but it is considered a bug fix)
Overriding `==` should use `Object` instead of `Object?` (revert https://github.com/felangel/equatable/pull/108) closes #115
```dart
@override
bool operator ==(Object other) {...}
```

fix: EquatableMixin == to use Object instead of Object?

---

.github/workflows/main.yaml

**READY**
NO
- ci: use very_good_workflows

ci: use very_good_workflows

---

.github/workflows/main.yaml
lib/src/equatable_utils.dart
test/equatable_test.dart

Fixes #141
**READY**
NO
This fixes the inconsistent hashCode behaviour for Sets by using a SplayTreeSet to ensure a consistent iteration order.
See #141
None known

fix: use SplayTreeSet to resolve inconsistent hashCode

---

lib/src/equatable_utils.dart
test/equatable_test.dart

**READY**
NO
- fix: props are not of type Comparable

fix: props are not of type Comparable

---

lib/src/equatable_mixin.dart

**READY**
NO
- fix: add `@immutable` to `EquatableMixin`

fix: add @immutable to EquatableMixin

---

lib/src/equatable.dart
lib/src/equatable_mixin.dart

**READY**
NO
The goal is to simplify toString method on `Equatable` and `EquatableMixin` and remove repetitive logic.

refactor: simplify `toString` logic

---

benchmarks/README.md
lib/src/equatable.dart
test/equatable_test.dart

**READY**
YES
- feat: use `covariant` in `operator==` override for improved type safety (closes #177)

feat: use `covariant` in `operator==` override for improved type safety

---

CHANGELOG.md
LICENSE
pubspec.yaml

chore: v2.0.6

---

lib/src/equatable_utils.dart
test/equatable_utils_test.dart

**READY**
NO
- revert: `equals` in `equatable_utils` even though this was not a breaking change it appears there are other tools that specifically depended on this internal utility. (#187)

revert: `equals` in `equatable_utils`
