CHANGELOG.md, README.md, example/main.dart, lib/equatable.dart, lib/src/equatable.dart, lib/src/equatable_mixin.dart, lib/src/equatable_utils.dart, pubspec.yaml, test/equatable_mixin_test.dart
**READY**
NO
Add `EquatableMixinBase` and `EquatableMixin` (#4)
None
=> Add EquatableMixin

lib/src/equatable_utils.dart
=> fix typo in utils

CHANGELOG.md, lib/src/equatable_utils.dart, pubspec.yaml, test/equatable_mixin_test.dart, test/equatable_test.dart
**READY**
NO
`Equatable` instances that are equal now have the same `hashCode` (#8)
None
=> Fix hashCode bug

README.md, test/equatable_test.dart
test: add test for json
READY
NO
More information and test about work with json
=> docs: add more information about work with json (#10)

CHANGELOG.md, README.md, pubspec.yaml
**READY**
NO
Addresses #14 
None
=> Update README to reference ^0.2.0

README.md
READY
NO
I noticed there is a new version but it was not reflected in the documentation. 
Thanks for the great work, the latest change to Jenkins hash is a great improvement.
List related PRs against other branches:
* documentation
=> pump version in readme.md

README.md
**READY**
NO
Added a note (from gitter)
=> Add note/link about mutable hashCodes

.github/workflows/main.yaml, README.md, coverage_badge.svg, pubspec.yaml
**READY**
NO
- Update CI to use Github Actions
=> ci: switch to github actions

README.md
**READY**
NO
A few sentences describing the overall goals of the pull request's commits.
=> docs: Make constructor constants

doc/migration_guides/migration-0.6.0.md
**READY**
NO
A few sentences describing the overall goals of the pull request's commits.
=> docs: migration docs change

CHANGELOG.md, lib/src/equatable_utils.dart, pubspec.yaml, test/equatable_test.dart
**READY**
NO
- fix: prop of type Map with non-comparable key (closes #119)
=> fix: prop of type Map with non-comparable key

.github/workflows/main.yaml
**READY**
NO
- ci: verify pub score
=> ci: verify pub score

CHANGELOG.md, pubspec.yaml
=> chore: v2.0.3

pubspec.yaml
**READY**
NO
- chore(deps): remove unused coverage dev dependency
=> chore(deps): remove unused coverage dev dependency

.github/workflows/main.yaml
**READY**
NO
- ci: upgrade to flutter-action@v1.5.3
=> ci: upgrade to flutter-action@v1.5.3

test/equatable_test.dart
**READY**
NO
- test: add tests for nested Iterable
=> test: add tests for nested iterable

CHANGELOG.md, pubspec.yaml
=> chore: v2.0.4

CHANGELOG.md, pubspec.yaml
=> chore: v2.0.5

analysis_options.yaml, example/main.dart, example/pubspec.yaml, lib/src/equatable.dart, lib/src/equatable_config.dart, lib/src/equatable_mixin.dart, lib/src/equatable_utils.dart, test/custom_list.dart, test/equatable_mixin_test.dart, test/equatable_test.dart
**READY**
NO
refactor: update `analysis_options.yaml`
=> refactor: update `analysis_options.yaml`

lib/src/equatable_config.dart
=> chore: fix typo in doc comment

pubspec.yaml
**READY**
NO
- chore: add `funding` and `topics` to `pubspec.yaml`
=> chore: add `funding` and `topics` to `pubspec.yaml`

lib/src/equatable_utils.dart, test/equatable_utils_test.dart
**READY**
NO
- fix: explicitly handle `num` equality comparisons (related to #188)
=> fix: explicitly handle `num` equality comparisons

CHANGELOG.md, pubspec.yaml
=> chore: v2.0.7
